### ISSUE TITLE
Refine Interactions views

### ISSUE THREAD

**Issue by shah** [tech-by-design/polyglot-prime#100]
After finishing #101, the Interactions UX needs to be updated:

- [x] the `FHIR via HTTPs` grid should only show FHIR interactions (not all URIs)
- [x] add new `HTTP` grid that would show all HTTP(s) interactions

**Comment by vinodaravind01** [comment]
- Updated the FHIR via HTTPs grid to display only FHIR interactions, excluding all other URIs.
- Added a new HTTP grid to show all HTTP(s) interactions.
These changes will be updated to the stage environment in version 0.105.0
