### ISSUE TITLE
Migrate all AG Grid pages to common modules

### ISSUE THREAD

**Issue by shah** [tech-by-design/polyglot-prime#101]
- [x] Switch over all AG Grid pages to use new `AGGridAide` and common modules infrastructure (see [this commit](https://github.com/tech-by-design/polyglot-prime/commit/ed99c988a5eaf301d9fa8438586bcf1033dfd23c) as an example). 
  - [x] only turn on columns (sorting) and filters initially - `lib.aide.sql.dynamic.SqlQueryBuilder` is currently broken for pivots and might not work for groups either but sorting and filters should work
  - [ ] after initial migrations complete, review groups definition and SQL generation (see `SqlQueryBuilderTest` to prepare unit tests first)
  - [ ] after groups definition complete, review pivot definition and SQL generation (see `SqlQueryBuilderTest` to prepare unit tests first)
- [x] Delete all unnecessary _controller class methods_ (now the single `org.techbd.service.http.hub.prime.ux.DynamicSqlQueryController::aggridContent()` replaces all other Controllers which have custom methods for retrieving data for AG Grid)
- [x] Delete all unnecessary _controller classes_ if no methods remain
- [x] Delete `hub-prime/src/main/java/org/techbd/service/http/aggrid` after all unused controllers and methods are deleted (`hub-prime/src/main/java/lib/aide/sql/dynamic` fully replaces `org/techbd/service/http/aggrid`);

**Comment by vinodaravind01** [comment]
- Added missing columns in ag-Grid and used the correct stored view, update views .
- Removed unused API endpoints.

These changes will be updated to the stage environment in version 0.103.0

**Comment by vinodaravind01** [comment]
- Deleted unnecessary controller class methods,
- Removed `hub-prime/src/main/java/org/techbd/service/http/aggrid `folder.
- Migrated diagnostics AG Grid pages to common modules for consistency
- Cleaned up codebase by removing commented code.

These changes will be updated to the stage environment in version 0.105.0

**Comment by shah** [comment]
Closing because most of this ticket is complete; the remainder of the open checkboxes will be completed as part of #109.
