### ISSUE TITLE
Introduce type-safe generalized AG Grid ("tabular") rows supplier

### ISSUE THREAD

**Issue by shah** [tech-by-design/polyglot-prime#109]
- [x] Generalize AG Grid ("tabular") rows supplier to an interface which supports multiple suppliers
- [x] Create simplified Java `record`s which model AG Grid server-side row requests and responses
- [x] Implement a `JooqRowsSupplier` which accepts a JSON row request and creates dynamic SQL response
- [x] Switch over all AG Grid pages to use new `TabularRowsController` endpoints (see [aggrid-aide.html experiment file](https://github.com/tech-by-design/polyglot-prime/commit/a708b812e78d3305496d227b6cce6abfa6c195f9#diff-843377799bf1061ee0f7d18bcb02e3c3f88e3608e70a422b8bfc18f3a711af6c) instructions to change the endpoints).
  - [x] only turn on columns (sorting) and filters initially - `lib.aide.tabular.JooqRowsSupplier` is currently broken for pivots and might not work for groups either but sorting and filters should work
- [x] Delete `DynamicSqlQueryController` since it's replaced by `TabularRowsController`.
- [x] Delete `hub-prime/src/main/java/lib/aide/sql/dynamic` package after `DynamicSqlQueryController` is deleted (the generalized `hub-prime/src/main/java/lib/aide/tabular` fully replaces `hub-prime/src/main/java/lib/aide/sql/dynamic`)

**Comment by shah** [comment]
@vinodaravind01 this is ready for you to implement.

**Comment by vinodaravind01** [comment]
- Switched over all AG Grid pages to use new TabularRowsController endpoints.
- Deleted `DynamicSqlQueryController`.
- Deleted the `hub-prime/src/main/java/lib/aide/sql/dynamic` package.
