### ISSUE TITLE
Introduce Data Quality UX

### ISSUE THREAD

**Issue by shah** [tech-by-design/polyglot-prime#120]
_Diagnostics_ is too technical a term and this section of the UI is meant for _content_ or _data quality_ so let's introduce that user experience. Specifically:

- [x] Rename _Diagnostics_ menu to _Data Quality_
- [x] Create `FHIR Data Quality` tab which would allow QEs to see their FHIR content / data quality issues
- [x] Create `Flat File (CSV) Data Quality` tab which would allow QEs to see their flat file content / data quality issues in CSVs

**Comment by shah** [comment]
@alan-francis are line numbers available in our diagnostics which can be shown in our Data Quality views?

**Comment by alan-francis** [comment]
> @alan-francis are line numbers available in our diagnostics which can be shown in our Data Quality views?

Yes @shah , we can give row numbers together with the column numbers to be shown in our  Data Quality views. Will update this into the view immediately.

**Comment by raphaelvp** [comment]
Implemented in v0.110.0
