### ISSUE TITLE
Resolve SpotBugs Bug Detector Report

### ISSUE THREAD

**Issue by razakpm** [tech-by-design/polyglot-prime#190]
Resolve issues reported by spot bug detector.
Details we can see in the URL which s listed in https://synthetic.fhir.api.devl.techbd.org/docs/project and select Project Reports > SpotBugs

**Comment by shah** [comment]
@razakpm @ratheesh-kr we may want to turn off `MALICIOUS_CODE` `EI_EXPOSE_REP` warnings because they're not serious enough. Before you proceed to make those fixes, discuss with me.

**Comment by razakpm** [comment]
Created an exclusion for MALICIOUS_CODE and EI_EXPOSE_REP warnings listed in https://synthetic.fhir.api.devl.techbd.org/docs/project because they're not serious enough. Resolved almost all other bugs.
