### ISSUE TITLE
For Java Maven projects publish `mvn site` results to GitHub Pages

### ISSUE THREAD

**Issue by shah** [tech-by-design/polyglot-prime#2]
See: [Publishing a Maven Site to GitHub Pages](https://www.lorenzobettini.it/2020/01/publishing-a-maven-site-to-github-pages/).

Take output of `mvn site` static HTML (stored in `target/site` by default) and publish at `github.com/tech-by-design/polyglot-prime` GitHub Pages at `https://tech-by-design.github.io/polyglot-prime/` with every build.

**Comment by resulraveendran** [comment]
@shah 
Published the static HTML output of mvn site to GitHub Pages. The static content generated and stored in the target/site directory is now automatically published to the GitHub Pages site at https://tech-by-design.github.io/polyglot-prime/ with every build.I have submitted a [merge request](https://github.com/tech-by-design/polyglot-prime/pull/9) for this update. Please review and approve, and kindly follow the description provided.

**Comment by shah** [comment]
Thank you @resulraveendran I've merged the PR but the build is broken, please see https://github.com/tech-by-design/polyglot-prime/actions/runs/9273071323/job/25512453884.
