### ISSUE TITLE
Add 'IG Publication Issues' grid to show the publication issues

### ISSUE THREAD

**Issue by raphaelvp** [tech-by-design/polyglot-prime#350]
Create `IG Publication Issues` grid page to show the distinct errors and counts focused on "URL not found" type of issues.

The following fields need to be added in the page
- Validation Engine (e.g. HAPI 7.x)
- Issue (the message from the Validator)
- Most Recent Date
- Count Of Interactions (Optional if the performance is not bad)

**Comment by ratheesh-kr** [comment]
Released in version 0.188.0
