### ISSUE TITLE
Remove Inferno Java sources in favor of bundled JAR

### ISSUE THREAD

**Issue by shah** [tech-by-design/polyglot-prime#36]
Let's investigate why we need the Inferno source files in our tree (`hub-prime/src/main/java/org/inferno`) and:

- [x] remove inferno sources in favor of Maven JARs
- [x] remove `hub-prime/igs`
- [x] cleanup `pom.xml` to remove JARs such as `gson` that were added for this library

**Comment by raphaelvp** [comment]
Resolved in v0.96.0
