### ISSUE TITLE
Add HTTP endpoint to accept and process HL7v2 message data

### ISSUE THREAD

**Issue by raphaelvp** [tech-by-design/polyglot-prime#412]
- [x] Define and update data models to support the ingestion of HL7v2 data
 - [x] Implement API endpoint to accept and process HL7v2 message data and integrate

**Comment by pat-johnson-dev** [comment]
Please verify you can open and review this.

[HL7 V2 Simplified Questionnaire Response.docx](https://github.com/user-attachments/files/17330686/HL7.V2.Simplified.Questionnaire.Response.docx)
