### ISSUE TITLE
Prepare New BizOps Feature Flags Infrastructure for accept/reject Bundle functionality

### ISSUE THREAD

**Issue by shah** [tech-by-design/polyglot-prime#466]
We need to turn on auto-rejection (not forward errors to SHIN-NY) and set up a new Business Operations (BizOps) Feature Flags infrastructure in our Help Desk. This infrastructure will allow application users to see and modify feature flags, starting with which messages to accept/reject, via a file in a GitHub repo.

- The feature flags file will be in YAML format for easy modification by end users (as opposed to JSON).
- The first file will be located at Help Desk Repo `feature-flag/non-sensitive-common.yml`.
- All other feature flags will be stored in `/feature-flag`, with non-sensitive, non-PHI content in `non-sensitive-common.yml`.

App Strategy:
- Create feature flags encapsulation using the existing Configuration class
- At start of the app, load the configuration for all feature flags
- In the _Console_ menu add new _Feature Flags_ tab to be able to see the flags
  - In the _Feature Flags_ tab allow reloading of file during application run

**Comment by shah** [comment]
The initial file has been created in Help Desk Repo `/feature-flag/non-sensitive-common.json5`.

**Comment by ratheesh-kr** [comment]
Updated and released in to stage
