### ISSUE TITLE
Utilize help@techbd.org email address

### ISSUE THREAD

**Issue by pat-johnson-dev** [tech-by-design/polyglot-prime#576]
Update the app to use [help@techbd.org](mailto:help@techbd.org) in place of `qcs-help@qualifiedentity.org` for any error messages or other areas where the help email is provided in user interface, API, or documentation.

**Comment by ratheesh-kr** [comment]
Updated and released in to Stage, PHI-QA

**Comment by ratheesh-kr** [comment]
Updated the email id.
