### ISSUE TITLE
New Tab/Rpt for Msgs by SCN

### ISSUE THREAD

**Issue by pat-johnson-dev** [tech-by-design/polyglot-prime#630]
On the Content page, add a tab for "SCN" (`/content/scn`).

The tab should have a grid with the following:
- Column 1: distinct SCN names that have sent screenings/referrals/assessments into TechBD
- Col 2: total number of msgs sent by SCN in Col 1.
- Col 3: number of successful msgs sent by SCN in Col 1.
- Col 4: number of failed msgs sent by SCN in Col 1.

Rows in the grid should be expandable (similar to how the Organization grid currently works) and when expanded, it should show the QE that the SCN sent msgs through in the first columns. Columns 2, 3, & 4 should carry down for each QE so that the SCN row acts as a "totals" row and the expanded rows would add up to that row.

As an example, the grid should look something like the following:
![image](https://github.com/user-attachments/assets/b5c0d161-6ce3-48a8-bbcb-ac3fa110be9d)

**Comment by ratheesh-kr** [comment]
Released in to PHI-QA version 0.338.0
