### ISSUE TITLE
Create the business rules for the flat files (CSV) as an Implementation Guide (IG) spec in a machine readable format

### ISSUE THREAD

**Issue by raphaelvp** [tech-by-design/polyglot-prime#652]
- [ ] Review the existing business rules specification for the flat file (CSV) data submission and compare it with the SHINNY IG.
- [ ] Identify the differences between the SHINNY IG spec and update the business rules to align it with the SHINNY IG specification.

**Comment by ratheesh-kr** [comment]
Released in 2024-12-05 update.
