### ISSUE TITLE
Searching for a FHIR message by bundle ID

### ISSUE THREAD

**Issue by alan-francis** [tech-by-design/polyglot-prime#694]
When using the FHIR Interactions via HTTPs view to search for a FHIR message:
https://synthetic.hub.stage.techbd.org/interactions/httpsfhir?continue

It would be helpful if it were possible to search by the bundleID from the FHIR message. The instanceID and the bundle ID do not appear to match.

There are instances where MRN is reused so it can be difficult to find the correct message without bundleID. Can bundleID be added to the view?

**Comment by ratheesh-kr** [comment]
Released in TechBD version 0.324.0
