### ISSUE TITLE
Accept multiple Content-type for incoming FHIR payloads

### ISSUE THREAD

**Issue by shah** [tech-by-design/polyglot-prime#72]
- [x] accept both `application/json` and `application/json+fhir` as incoming payloads
- [x] when forwarding requests, allow passing in a header request to override the content type
  - [x] if no header request override, use servlet request `getContentType()` to forward the same content type
  - [x] if no header request override and servlet request `getContentType()` are null then force to `application/json+fhir`
- [x] add `/Bundle` endpoints documentation

**Comment by shah** [comment]
@vinodaravind01 @anoopvarma-2000-p @ratheesh-kr I've implemented the code but did not have time to test it. Please review, test, then push to `devl` and `stage`.

**Comment by raphaelvp** [comment]
Released on v0.91.0
