### ISSUE TITLE
Project tab in Documentation Menu

### ISSUE THREAD

**Issue by ratheesh-kr** [tech-by-design/polyglot-prime#94]
Add "Project" tab and link  https://tech-by-design.github.io/polyglot-prime/

**Comment by raphaelvp** [comment]
Resolved in v0.98.0

**Comment by ratheesh-kr** [comment]
Update project documentation tab to use local target/site location for consistent environment-specific docs

**Comment by raphaelvp** [comment]
Resolved in v0.99.0
